### ISSUE TITLE
"Tap to reboot" and "Tap to power off"

### ISSUE THREAD

**Issue by elyorch76** [Acid-miuipolskapl/v6-XML-Compare#5]
Where are now the strings to translate "Tap to reboot" and "Tap to power off"?

**Comment by ingbrzy** [comment]
here https://github.com/MASVA/MA-XML-6.0-CROATIAN-master/blob/master/Croatian/extras/powermenu/strings/strings_hr_HR.xml

**Comment by elyorch76** [comment]
Ok thanks, then I think it was a problem with the 5.5.8 update
