### ISSUE TITLE
"Open music" and "No music" in the music notification widget

### ISSUE THREAD

**Issue by elyorch76** [Acid-miuipolskapl/v6-XML-Compare#6]
Is it possible to translate the strings "Open music" and "No music" in the music notification widget? (just above the toggles)

**Comment by ingbrzy** [comment]
yes.. place it like here https://github.com/MASVA/MA-XML-6.0-CROATIAN-master/blob/master/Croatian/extras/statusbar_music/strings/strings_hr_HR.xml

**Comment by elyorch76** [comment]
¿? no_title no_artist? What about "Open music" and "No music"?

**Comment by ingbrzy** [comment]
```
<strings>
    <string name="no_title" value="Open music player" />
    <string name="no_artist" value="No music" />
</strings>
```

**Comment by elyorch76** [comment]
Thanks!
